spring:
    application:
        name: card-rk
    cache:
        type: redis
        redis:
            time-to-live: 60000
            cache-null-values: true
    data:
        mongodb:
            uri: mongodb+srv://navlag:Fg3UgAroDl8SDVDt@avsavivd.lfqko.mongodb.net/pmactoob?retryWrites=true&w=majority
server:
    port: 8092

